cppgres/cppgres

cppgres/datum.h, cppgres/executor.h, cppgres/imports.h, cppgres/memory.h, cppgres/type.h, cppgres/types.h, tests/datum.h, tests/spi.h, tests/tests.cpp
I made a wrong assumption (having not thought it through) that any pointer behind a datum would be its own allocation. Of course it is not true. For example, when results returned from a query done over SPI, the data is allocated in tuples, not individually.
Solution: allow passing memory_context to from_nullable_datum/from_datum
This allows us to pass a _known_ memory context (if we do know it) to the constructor of the non-by-value type so that it can track it. We do this for SPI case because know the context there. In all other context, it'll assume top memory context, which is never reset.
=> Problem: tracking memory context for non-by-value types

cppgres/datum.h, cppgres/executor.h, cppgres/type.h, cppgres/types.h, cppgres/utils/utils.h, tests/datum.h
If one has to do some work on a complex type every time it is passed around, that's inconvenient and inefficient.
Solution: add support for expanded datums / varlenas
This brings a lot of changes to the core library.
=> Problem: having to reconstruct complex types

src/cppgres/datum.h, src/cppgres/executor.h, src/cppgres/imports.h, src/cppgres/syscache.h, src/cppgres/type.h, src/cppgres/types.h, tests/datum.h, tests/spi.h, tests/tests.cpp, tests/type.h
Solution: support convertible types explicitly
The defining test case is to implement `type_traits`. This required the introduction of `named_type` type to be able to find the type of interest. Combined into/from conversion in this trait.
Importantly, handled the case of a conflict with a PFR-derived tuples. If a type is convertible from nullable datum, and is the only attribute, it is not considered as a PFR tuple.
Implemented basic syscache lookup.
Fixed up error reporting.
=> Problem: can we use custom types?

src/cppgres/executor.hpp, src/cppgres/function.hpp, src/cppgres/set.hpp, test.sh, tests/function.hpp, tests/srf.hpp, tests/tests.cpp
This is not great as it becomes harder to not step on toes of other tests.
Solution: make them isolated in their own transactions
I had to fix up a few things for this to happen:
* Added a non-atomic SPI executor
* Started tracking current function to be able to tell its context
* Added support for void-returning functions
* Ensured we don't `ERROR`-report in `postgres_function` as we're not protected by our error guard correctly in that spot.
=> Problem: tests share the same transaction

CMakeLists.txt, cmake/FindPostgres.cmake, src/cppgres/executor.hpp, src/cppgres/function.hpp, src/cppgres/set.hpp, test.sh, tests/function.hpp, tests/srf.hpp, tests/tests.cpp
Set minimum version for cmake to 3.22 to work with ubuntu 22.04 LTS cmake version
=> Set minimum version for cmake to 3.22 to work with ubuntu 22.04 LTS cmake version

src/cppgres.hpp, src/cppgres/imports.h, src/cppgres/node.hpp, src/cppgres/utils/pfr.hpp, tests/node.hpp, tests/tests.cpp
We're forced to use C API. This is not very convenient.
Solution: prototype C++-like interface
For it to work, it requires embedding Boost.PFR. Would be great to avoid it, but not at all costs.
=> Problem: rudimentary understanding of Postgres nodes

src/cppgres/function.hpp, src/cppgres/imports.h, src/cppgres/syscache.hpp, tests/function.hpp
And that breaks our type checker – it can't make a decision whether anything's correct.
Solution: if that happens, look this information up in the syscache
There's a little bit of a caveat, it seems, with `_in` functions for types: the signature might contain just one argument but it seems Postgres is always specifying that it is calling with three arguments.
=> Problem: sometimes functions are called without type info

src/cppgres/function.hpp, src/cppgres/imports.h, src/cppgres/name.hpp, src/cppgres/record.hpp, tests/record.hpp
This would be very useful for record-returning functions.
Solution: add tuple_descriptor API
This also necessitated changes to `postgres_function` implementation as we want to be able to return sets of records.
=> Problem: can't create tuple descriptors

src/cppgres.hpp, src/cppgres/datum.hpp, src/cppgres/executor.hpp, src/cppgres/function.hpp, src/cppgres/record.hpp, tests/errors.hpp, tests/function.hpp, tests/record.hpp, tests/srf.hpp, tests/type.hpp
It's coming – available on some sets of platforms/compilers, but not everywhere.
Solution: allow to replace it with fmt if available
=> Problem: <format> availability is still choppy

src/cppgres.hpp, src/cppgres/threading.hpp, tests/tests.cpp, tests/threading.hpp
While Postgres is (still) single-threaded, we can't properly make use of C++'s and its ecosystem's multi-threading capabilities. But it would really be helpful to.
Solution: implement a generic "worker" to handle Postgres work
This worker is intended to work in a single thread and simply processes all incoming function calls to be executed in that thread.
=> Problem: use of threads

src/cppgres/backend.hpp, src/cppgres/imports.h, tests/backend.hpp, tests/tests.cpp
Feasible, but requires calling `on_proc_exit` from Postgres and does not allow to use closures.
Solution: provide a standardized API and allocate closures on the top memory context
=> Problem: cleaning up upon Postgres exit

src/cppgres/bgw.hpp, src/cppgres/datum.hpp, src/cppgres/executor.hpp, src/cppgres/function.hpp, src/cppgres/record.hpp, src/cppgres/types.hpp, tests/bgw.hpp, tests/function.hpp, tests/xact.hpp
It seem to have done this accidentally in some tests, but simply observing that we're iterating over `Args` to get types shows us that this is wrong.
Solution: ensure we actually iterate the return tuple types instead
This necessitated some signature changes (dropping `Args` is obvious) and promotion of `cppgres::oid` into a struct so we can implement correct conversion and type traits on it.
=> Problem: spi_executors result don't enforce return types

src/cppgres.hpp, src/cppgres/datum.hpp, src/cppgres/executor.hpp, src/cppgres/function.hpp, src/cppgres/record.hpp, src/cppgres/set.hpp, src/cppgres/type.hpp, src/cppgres/types.hpp, src/cppgres/value.hpp, tests/bgw.hpp, tests/datum.hpp, tests/function.hpp, tests/record.hpp, tests/spi.hpp, tests/srf.hpp, tests/type.hpp
Currently, spi_executor results work well when the data's shape is known: it can be mapped to a tuple, a struct, or a single value.
However, if we don't know much about the query, we can't get the results in a generalized way.
Solution: devise a type system for generalized value and metadata holding
=> Problem: unable to process SPI results in a generalized fashion 

src/cppgres/syscache.hpp, tests/syscache.hpp, tests/tests.cpp
`syscache` can be dereference to an underlying structure, but not all of its information is accessible through the struct, as they are only available using special routines.
Solution: add `get_attribute` method to retrieve & convert those
=> Problem: getting access to all syscache attributes

src/cppgres/executor.hpp, src/cppgres/utils/cstring.hpp
We do it regardless of how the string is supplied, even if it is a `const char*`, we still copy it. It's a non-zero cost and buys us nothing.
Solution: extract convertible_to_cstring from oomph
This allows us to convert strings on demand.
=> Problem: query string construction in executor

src/cppgres/function.hpp, tests/function.hpp
We can certainly make use of it, but it's not fitting the rest of the type system well – no iterable containers, pointer checking, etc.
Solution: wrap it with function_call_info
It's not complete nor fully optimal yet, but it gives us a direction.
=> Problem: FunctionCallInfo is not as useful in C++ land

src/cppgres/function.hpp
This might not be what the code that calls these might need.
Solution: use ranges to make it more generic
=> Problem: always allocating vectors in function_call_info

src/cppgres/function.hpp, tests/function.hpp
In `function_call_info` it is possible either to get arg datum iterator or arg type iterator, but not both.
While this is not a problem in C++23 (due to zip views), it's extra work and is not readily available in C++20.
Solution: use `value` type to represent the joined argument and expose it through `arg_values()`.
=> Problem: call info disjoining arg datums and arg types

src/cppgres/executor.hpp, src/cppgres/heap_tuple.hpp, src/cppgres/syscache.hpp, src/cppgres/xact.hpp, tests/heap_tuple.hpp, tests/tests.cpp, tests/tests.hpp
At times, there's a need to access heap tuple's header and its properties. For example, to get xmin, xmax, cmin, cmax.
An example: PLs (programing language handlers) often use xmin to determine if pg_proc entry has been updated to reload the cached code.
Solution: expose heap tuple in syscache and SPI
and provide a few common methods.
More methods and documentation to be added.
=> Problem: access to heap tuple header

src/cppgres.hpp, src/cppgres/aggregate.hpp, src/cppgres/datum.hpp, src/cppgres/record.hpp, src/cppgres/types.hpp, src/cppgres/value.hpp, tests/aggregate.hpp, tests/tests.cpp, tests/type.hpp
It's possible but involves a lot of manual work. The promise of this library, however, is to make things trivial.
Solution: design a conceptual API for it
It still misses a few things, like moving-aggregate mode, final func extra and so on.
This is a relatively large change that introduces a change to `datum_conversion` trait, adding `from_nullable_datum`, and introducing `default_datum_conversion` that removes some of the boilerplate. This is a good change as it vastly simplified `from_nullable_datum`, removing a lot of special-casing.
=> Problem: writing aggregates in C++

src/cppgres/memory.hpp, tests/memory_context.hpp
It's doable but we need to keep track of it and ensure we handle exception.
Solution: extract this into a simple operator() that does it all
=> Problem: executing code within a given memory context

src/cppgres/datum.hpp, src/cppgres/function.hpp, src/cppgres/imports.h, src/cppgres/type.hpp, src/cppgres/types.hpp, tests/function.hpp
One needs to call one of the C functions for a specific arity, convert arguments to and from datums and ensure that these functions are actually expecting these arguments.
Solution: wrap it all into a cppgres::function struct
It's a bit limited (no collation support at the moment) and I can see how it can grow further into these directions:
* direct function call (C)
* calling with tuples, arrays and vectors of arguments for dynamic cases
But it's a start.
Had to fix some mistakes and ommissions in optional <-> datum conversion (which is important!)
=> Problem: calling Postgres functions is somewhat painful

src/cppgres/datum.hpp, src/cppgres/function.hpp, src/cppgres/value.hpp, tests/function.hpp
Wouldn't it be cool to do type-safely call functions passed by users? For example, they can provide callbacks.
Solution: extend cppgres::function to support this case
Had to fix a few bugs to achieve this!
=> Problem: passing functional callbacks into functions

scripts/abi_layout.py
When we are checking for ABI, both C and C++ sizing for records was not captured and we were checking None with None.
We were still checking the offsets, though.
Solution: ensure our regexp captures it better
=> Problem: not reading C and C++ ABI dumps correctly

src/cppgres/memory.hpp, src/cppgres/type.hpp, tests/datum.hpp
Solution: let's write a tesst
Most important discovery: we weren't! Ensure we check whether it is an expanded pointer in T&() before trying to proceed and detoast.
While testing, found a few issues to fix:
1. Over-allocation of memory for reset callback in memory contexts
2. Don't inherit from `type` in `non_by_value_type` – they are different hierarchies. Ideally, we shouldn't call it `_type`, it doesn't describe a type but value.
3. Initialize expandable object in its own memory context
Also, decided to use argument forwarding to initialize the `inner` part of the expanded object.
=> Problem: unsure if expandable value avoids flattening

src/cppgres/executor.hpp, tests/spi.hpp
```c++
spi.query<...>("query", val1, val2, val3);
```
Results in passing more than one argument to `type_traits<valN>`.
Solution: ensure we expand pack correctly
=> Problem: can't compile multi-parameter query

src/cppgres/threading.hpp
`gettid()` is not defined
Solution: ensure we specify _GNU_SOURCE
to enable this functionality
=> Problem: can't compile on some systems

src/cppgres/threading.hpp
Solution: define it only if it isn't
=> Problem: warning about overriding _GNU_SOURCE if defined
